### ISSUE TITLE
Progress 3D Design (ViewPort)

### ISSUE THREAD

**Issue by HaqifalHS** [HaqifalHS/Audio-Digital-Project#1]
**DESAIN3D**

**Comment by 025Farhan** [comment]
![Image](https://github.com/HaqifalHS/Audio-Digital-Project/assets/169011190/aca36bbf-a7fb-472e-90b0-68958428fb1d)

**Comment by 025Farhan** [comment]
![Image](https://github.com/HaqifalHS/Audio-Digital-Project/assets/169011190/0c3ab5ed-4de7-40be-8071-4efe5af064d1)

PROGRESS PERTAMA

**Comment by 025Farhan** [comment]
![Image](https://github.com/HaqifalHS/Audio-Digital-Project/assets/169011190/e553bf1d-d4fb-43c4-8c54-73def8d67e1d)

Final
