### ISSUE TITLE
Bikin AUDIO rekaman

### ISSUE THREAD

**Issue by HaqifalHS** [HaqifalHS/Audio-Digital-Project#5]

**Comment by hanbima21** [comment]
[Audacity.zip](https://github.com/HaqifalHS/Audio-Digital-Project/files/15288840/Audacity.zip)

**Comment by hanbima21** [comment]
[Project Mikrokontroller.zip](https://github.com/HaqifalHS/Audio-Digital-Project/files/15289090/Project.Mikrokontroller.zip)

Pada pembuatan audio ini dibuat menggunakan software AUDACITY dengan versi 3.5. Rekaman audio ini di setting dengan Sample Rate 8kHz, Default Sample Format 32-bit float. Pada proyek ini dilakukan 2 rekaman untuk 2 kondisi yaitu kondisi Masuk dan kondisi Keluar. Untuk audio Masuk yaitu "Selamat datang di toko kami", untuk audio Keluar yaitu "Terimakasih sampai jumpa".

**Comment by hanbima21** [comment]
[AUDIO](https://github.com/HaqifalHS/Audio-Digital-Project/files/15370144/Project.Audio.Mikrokontroler.zip)

Pada pembuatan audio dibuat menggunakan software 'AUDACITY' versi 3.5. Sinyal audio ini direkam dengan format raw 8 bit 1 Channel Mono dengan Sample Rate 8kHz. Pada project kali ini dilakukan 2 rekaman untuk 2 kondisi yaitu kondisi Masuk dan kondisi Keluar. Untuk audio Masuk yaitu "Selamat datang di toko kami", untuk audio Keluar yaitu "Terimakasih sampai jumpa".

DOCUMENTATION
1. [Audacity_Selamat_Datang](https://github.com/HaqifalHS/Audio-Digital-Project/assets/161258021/7bf1ef37-c573-4fea-8560-8e1d9d362dbb)
2.  [Audacity_Terimakasih](https://github.com/HaqifalHS/Audio-Digital-Project/assets/161258021/24d1904c-bbbf-4572-976e-9d5e8db8de21)


*klik 'AUDIO' untuk memperoleh ZIP project

**Comment by hanbima21** [comment]
Cara untuk mengatur sample rate:
1. Klik Edit
2. Klik Preference
3. Atur Sample rate menjadi '8000 Hz'

DOCUMENTATION
[Setting_Audacity](https://github.com/HaqifalHS/Audio-Digital-Project/assets/161258021/246bb7bc-8b03-4297-a374-20ff9bff1ba5)

**Comment by hanbima21** [comment]
Cara untuk save rekaman format RAW:
1. Klik File
2. Klik Export Audio
3. Klik Export to Computer
4. Pada format pilih 'Other uncompressed files'
5. Pada header pilih 'RAW (header-less)
6. Pada encoding pilih 'Signed 8-bit PCM'
7. Terakhir klik export

DOCUMENTATION
[Format RAW](https://github.com/HaqifalHS/Audio-Digital-Project/assets/161258021/bcf26ad9-18a2-4038-a517-b94c156b1841)

**Comment by hanbima21** [comment]
Video Audio to Hex

https://github.com/HaqifalHS/Audio-Digital-Project/assets/161258021/f7ce8587-4347-4032-91a0-f2add8da7c45
